FROM mcr.microsoft.com/mssql/server:2019-latest

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=5miKT_X`Y3~mZ%UDFo\z6;8gp]CCUGoZd^|L[a1n
ENV MSSQL_PID=Express

COPY ["Pitcher8.mdf", "E:\\OneDrive\\Work\\Programming Experiments\\DockerDatastore\\Pitcher8.mdf"]
COPY ["Pitcher8_log.ldf", "E:\\OneDrive\\Work\\Programming Experiments\\DockerDatastore\\Pitcher8_log.ldf"]

EXPOSE 1433